# Generated by Django 3.0.3 on 2023-03-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='DinnerPlatters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price_small', models.DecimalField(decimal_places=2, help_text='Price in US dollars', max_digits=5)),
                ('price_large', models.DecimalField(decimal_places=2, help_text='Price in US dollars', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('dishtype', models.CharField(max_length=32)),
                ('dishname', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in US dollars', max_digits=5)),
                ('remarks', models.TextField()),
                ('status', models.CharField(max_length=32)),
                ('send_message', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in US dollars', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Salads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in US dollars', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='SubExtras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in US dollars', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price_small', models.DecimalField(decimal_places=2, help_text='Price in US dollars', max_digits=4)),
                ('price_large', models.DecimalField(decimal_places=2, help_text='Price in US dollars', max_digits=4)),
                ('extras', models.ManyToManyField(blank=True, to='orders.SubExtras')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('style', models.CharField(choices=[('R', 'Regular'), ('D', 'Dinosaur')], max_length=1)),
                ('price_small', models.DecimalField(decimal_places=2, help_text='Price in US dollars', max_digits=5)),
                ('price_large', models.DecimalField(decimal_places=2, help_text='Price in US dollars', max_digits=5)),
                ('toppings', models.ManyToManyField(blank=True, to='orders.Catagories')),
            ],
        ),
    ]
