# Generated by Django 3.0.3 on 2023-03-31 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='dishname',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='dishtype',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
    ]
