# Generated by Django 3.0.3 on 2023-03-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20230331_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='000', max_length=5),
            preserve_default=False,
        ),
    ]
