# Generated by Django 3.0.3 on 2022-11-01 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20221031_2057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toppings',
            new_name='Catagories',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='toppings',
            new_name='catagories',
        ),
    ]
