# Generated by Django 3.0.3 on 2022-11-01 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20221101_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toppings',
            new_name='Catagories',
        ),
    ]
